week 4 assessment
learn-academy-2023-delta/week-4-assessment-yungRicardo pull request #1
Opened 2023-06-07 17:03 UTC by yungRicardo

# Submitting Week 4 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ ] Coding Concepts
- [ ] Interview Questions

### ✋ Reminder

Do NOT merge your assessment!

### 📝 Feedback

If you would like specific feedback please leave details here:

2023-06-07 18:26 UTC, chrisyhlee requested changes
Missing a test for Javascript 3. This is probably the reason you didn't catch that your function is not working how you want it to as well. Please make the changes and resubmit

2023-06-07 18:26 UTC, chrisyhlee commented on code-challenges.test.js
> +// Return array with sort method to shuffle the rest, using Math.random()
Nice job, I'm a fan of the short but sweet pseudo code

2023-06-07 18:26 UTC, chrisyhlee commented on code-challenges.test.js
> +// return totalTally
no need to make the variable, just return

2023-06-07 18:26 UTC, chrisyhlee commented on code-challenges.test.js
> +//we merge the the 2 arrays together using spread syntax and invoke dataTypes passing the mergedArr as a argument.
Nice attempt! Very close. I would pay attention to what you are receiving from `...data`. Make sure to console.log each step so you can see what each piece of code is returning and is what you're expecting.

2023-06-07 18:26 UTC, chrisyhlee commented on interview-questions.md
> +Your answer: to extract a value from a hash you must find the key that you trying to access.
I suggest giving more elaborate answers in all of your interview questions. Give an example of how to use it, and you can include how you personally have experience with the concept being asked about. The goal is for the interviewer to know that you know what you're talking about without a doubt.

2023-06-07 18:26 UTC, chrisyhlee commented on ruby-challenges.rb
> +        puts "#{str} is not a palindrome"
Make sure you don't leave any `puts` or `p` within your methods. It's essentially the same as leaving in console.logs in Javascript, which is bad practice.

2023-06-08 17:47 UTC, chrisyhlee approved these changes
Thanks for making the requested changes. This assessment displays Advanced Beginner, but will be marked down to Novice because of tardiness. Take another look at your refactor for JS 3 and see why it's not working properly, it has to do with the spread operator in the parameter, which is probably not outputting what you think it is. You are approved to merge and delete the branch. I would focus on making your interview questions more elaborate by adding in examples and your personal experience with the concept being asked about. Otherwise good work!

2023-06-08 19:22 UTC, merged

2023-06-08 19:23 UTC, yungRicardo commented
Could you please help me understand what I'm missing in JS challenge 3 please. I thought i fixed the problem

2023-06-08 20:11 UTC, chrisyhlee commented
Sure, so if you console log what you have right now `console.log([...new Set(...data)] )`, you can see what it's returning, which is just the first array. So it's completely ignoring the second array entirely. To fix this, we need to combine the two arrays into one array, like we did during review. You can do this: `return [...new Set([].concat(...data))]`. This will take all the arrays passed into the function and put every value into one single array, and from there, we throw it in a Set to remove duplicates, and then use the spread operator in another array to put the Set values in an array. Hope this helped clarify some things, if there's still some confusion I'm happy to explain further.